version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
      - type: bind
        source: ./
        target: /workdir